# Generated by Django 5.0.1 on 2024-02-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restrooms',
            new_name='Restroom',
        ),
    ]
