# Generated by Django 5.0.1 on 2024-02-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_restrooms_restroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restroom',
            name='name',
        ),
        migrations.AlterField(
            model_name='restroom',
            name='location',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
