# Generated by Django 5.0.1 on 2024-02-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_restroom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restroom',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
